// Generated by dts-bundle v0.7.3

/**
  * Path Exemple
  * ----------
1 -  patient.age.cm
2 - patient.medicalCondition[1]
3 - patient.medicalCondition[mapOrSetKey]
4 - patient.getAgeMonth()
  */
type Token = {
    segment: string;
    type: "property" | "array" | "function" | "mapOrSet";
    arrayIndex?: number;
    mapOrSetKey?: string | number | undefined;
    functionArgs?: any[];
};
export class PathResolver<T> {
    constructor(context: T);
    resolve<R = any>(path: string): Promise<R>;
    _resolve(tokens: Token[], context: any, counter: number): Promise<any>;
}
export {};

export class Utils {
    static isAsyncFunction(fn: Function): boolean;
    static isFunctionSegment(segment: string): boolean;
    static isArraySegment(segment: string): boolean;
    static isObject(value: any): boolean;
    static isFunction(value: any): boolean;
    static isArray(value: any): boolean;
    static isMap(value: any): boolean;
    static isSet(value: any): boolean;
}

